model_name_or_path: "./parler-tts-ko/parler-tts-untrained-600M/"
feature_extractor_name: "parler-tts/dac_44khZ_8kbps"
description_tokenizer_name: "google/flan-t5-large"
prompt_tokenizer_name: "./parler-tts-ko/parler-tts-untrained-600M/"
report_to: "mlflow"
overwrite_output_dir: true
train_dataset_name: "channelcorp/aihub_tts_012+channelcorp/aihub_tts_001+channelcorp/aihub_tts_011+channelcorp/aihub_tts_009+channelcorp/aihub_tts_007+channelcorp/aihub_tts_024+channelcorp/aihub_tts_186"
train_split_name: "train+train+train+train+train+train+train"
eval_dataset_name: "channelcorp/aihub_tts_012+channelcorp/aihub_tts_001+channelcorp/aihub_tts_011+channelcorp/aihub_tts_009+channelcorp/aihub_tts_007+channelcorp/aihub_tts_024+channelcorp/aihub_tts_186"
eval_split_name: "validation+validation+validation+validation+validation+validation+validation"
sharded: true
target_audio_column_name: "audio"
prompt_column_name: "transcription"
max_duration_in_seconds: 30
min_duration_in_seconds: 2.0
max_text_length: 600
add_audio_samples_to_wandb: true
id_column_name: "id"
preprocessing_num_workers: 24
do_train: true
num_train_epochs: 25
logging_steps: 10
gradient_accumulation_steps: 4
gradient_checkpointing: false
per_device_train_batch_size: 24
learning_rate: 0.0015
adam_beta1: 0.9
adam_beta2: 0.99
weight_decay: 0.01
lr_scheduler_type: "constant_with_warmup"
warmup_steps: 5000
freeze_text_encoder: true
do_eval: true
predict_with_generate: true
include_inputs_for_metrics: true
evaluation_strategy: "steps"
eval_steps: 250
save_steps: 250
per_device_eval_batch_size: 24
audio_encoder_per_device_batch_size: 24
dtype: "bfloat16"
seed: 456
output_dir: "./output_dir_training/"
temporary_save_to_disk: "./audio_code_tmp/"
save_to_disk: "./tmp_dataset_audio/"
max_eval_samples: 36
dataloader_num_workers: 8
group_by_length: true
attn_implementation: "sdpa"
streaming: false
