compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
 deepspeed_config_file: helpers/multinode/deepspeed_config_zero2.json
 zero3_init_flag: false
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: main1
main_process_port: 29500
rdzv_backend: static
same_network: true
main_training_function: main
num_machines: 1
num_processes: 4
use_cpu: false
